name: Streamly Python Workflow

on:
  push:
    branches:
      - main

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Python script
      env:
        STREAMLIT_TOKEN: ${{ secrets.STREAMLIT_TOKEN }}  # Referencing the secret
      run: |
        python TruckKun/truckkun.py
